runtime: python311 # or another supported version

instance_class: F1

automatic_scaling:
  min_instances: 1
  max_instances: 1

env_variables:
  FLASK_BACKEND_ENV: "PROD"

handlers:


- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto



service: api-0
service_account: app-engine-deployer-0@[PROJECT_NAME].iam.gserviceaccount.com
