include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "Windmillcode_app_tutorials/**"

linter:
  rules:
    # You can enable or disable additional lint rules here.
    # For a list of available lint rules, see: https://dart.dev/tools/linter-rules
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    await_only_futures: true
    constant_identifier_names: false



flutter:
  rules:
    avoid_unnecessary_containers: true
    avoid_using_show_menu: true
    no_logic_in_create_state: true
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    unused_local_variable: false

